name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache uv and venv
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: |
          .venv/
        key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install uv and set up venv (if cache missed)
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        pip install uv
        uv venv
        uv pip install -r requirements.txt

    - name: Run linter (ruff)
      run: |
        .venv/bin/ruff check src/ tests/

    - name: Run tests (pytest)
      run: |
        .venv/bin/pytest tests/

    - name: Download Mermaid.js
      run: |
        mkdir -p docs/_static/js
        curl -L https://cdn.jsdelivr.net/npm/mermaid@10.9.0/dist/mermaid.min.js -o docs/_static/js/mermaid.min.js

    - name: Build documentation (Sphinx)
      run: |
        .venv/bin/sphinx-build -b html docs/ public/

    - name: Upload built documentation
      uses: actions/upload-artifact@v4
      with:
        name: built-docs
        path: public/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Download built documentation
        uses: actions/download-artifact@v4
        with:
          name: built-docs
          path: public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
