name: Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv and dev dependencies
        run: |
          pip install uv
          uv venv
          uv pip install --group dev

      - name: Build distributions
        run: |
          source .venv/bin/activate
          python -m build --sdist --wheel

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: dist/
